# Generated by Django 4.2 on 2023-04-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_department_id_alter_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
